### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by dixantmittal** [mstallmo/tensorrt-rs#47]
Hi! Thanks for building this library. I am using TensorRT in my project written in python. Now, I am porting my project from python to rust and want to use this repo, but I am not able to import it using cargo.toml. I suspect this could be a cuda version mismatch or device not supported issue. I'd like to seek your help in building it.

He is my environment:
 - Model: RTC 2080 Ti
 - OS: Ubuntu 18.04
 - CUDA Version 11.2
 - CUDNN Version 8.1.1.33-1+cuda11.2
 - TensorRT Version 7.2.3-1+cuda11.1
 

In cargo.toml, I'm using
```
[dependencies]
tensorrt-rs = {git="https://github.com/mstallmo/tensorrt-rs" , branch="develop"}
```

This is the error I get when building.

![image](https://user-images.githubusercontent.com/13286090/115866332-19ba6000-a46c-11eb-90a1-69524cd287c8.png)

Thanks again for working on this repo!

Regards,
Dixant

**Comment by mstallmo** [comment]
Hi Dixant,

So it looks like the root cause is an unsupported architecture in the newer nvcc. `sm_30` support was recently dropped by nvcc. You  should be good from a hardware standpoint since the 2080Ti is `sm_70`. This is most likely an issue with a library version.   

What feature flags did you use when building the crate?

**Comment by dixantmittal** [comment]
Hi @mstallmo,

Thanks for looking into the issue. I solved it sometime back. There was some issue with CMAKE not able to detect TensorRT headers. Anyways, thanks for the help!
